server:
  #端口
  port: 80
spring:
  mvc:
    static-path-pattern: /resources/**
  thymeleaf:
    #配置视图解析器
    #prefix: classpath:/templates/
    #check-template-location: true
    #suffix: .html
    #页面热加载
    cache: false
    encoding: UTF-8
    #mode: HTML
    #配置数据库
  datasource:
    url: jdbc:mysql://139.196.110.93:3306/videoweb
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.gqchen.bean
  #识别Mapper.xml文件
  mapper-locations: classpath*:mapper/*.xml
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true